version: '3'
services:
  mysql:
    image: mysql:5.7
    command: --explicit_defaults_for_timestamp=1
    container_name: mysql_container
    env_file:
     - ./Docker/api/api.env
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=jupyterhub
      - MYSQL_USER=jupyterhub
      - MYSQL_PASSWORD=123456  
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
hub:
    depends_on:
      - mysql
    build: .
    container_name: jupyterhub
    environment:
     - TERM=xterm
    volumes:
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    ports:
      - 8080:8000
    links:
      - mysql:mysql
    restart: always
volumes:
  mysql-data:
    driver: local