version: '3'
services:
  app:
    container_name: malllog-main
    restart: always
    build: .
    ports:
      - '3000:3000'
    external_links:
      - mongo
      - redis
      - rabbitmq
  mongo:
    container_name: malllog-mongo
    image: mongo:4.4
    ports:
      - '27017:27017'
  redis:
    container_name: malllog-redis
    image: redis:4.0.6
    ports:
      - '6379:6379'
  rabbitmq:
    container_name: malllog-rabbitmq
    image: rabbitmq:3.8.9
    ports:
      - '15672:15672'
      - '5672:5672'